In [ ]:
import numpy as np

In [ ]:
myArr = np.array([2, 4, 6, 3, 55, 23, 33])
print(myArr)


[ 2  4  6  3 55 23 33]


In [ ]:
TwoDArr = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(TwoDArr)


[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [ ]:
arr = np.zeros(10, dtype=int)
print(arr)


[0 0 0 0 0 0 0 0 0 0]


In [ ]:
arr = np.ones((5,3), dtype='float32')
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.arange(0, 20, 2)
print(arr)
arr = np.linspace(0, 1, 5)
print(arr)
arr = np.random.random((3,3))
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[0.66471841 0.55059971 0.23652802]
 [0.20402302 0.65822415 0.48651941]
 [0.32722864 0.7374309  0.88697982]]


In [ ]:
arr1 = np.random.randint(1,10, size=10)
print(arr1)
arr2 = np.random.randint(1,10, size=10)
print(arr2)
arr3 = arr1 - arr2
print(arr3)

result = np.dot(arr1, arr2)
print(result)

[2 1 3 6 1 3 7 7 1 8]
[5 3 8 1 2 1 6 6 2 9]
[-3 -2 -5  5 -1  2  1  1 -1 -1]
206


In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("SampleData.csv")
#print(data)

units = np.array(data['Units'])
unit_cost = np.array(data['Unit Cost'])

total = units * unit_cost

print(total)


[ 189.05  999.5   179.64  539.73  167.44  299.4   149.25  449.1    63.68
  539.4   449.1    57.71 1619.19  174.65  250.    255.84  251.72  575.36
  299.85  479.04   86.43 1183.26  413.54 1305.     19.96  139.93  249.5
  131.34  479.04   68.37  719.2   625.    309.38  686.95 1005.9   825.
    9.03  151.24 1139.43   18.06   54.89 1879.06  139.72]


In [ ]:
print(units)
temp = units + 5
print(temp)

[95 50 36 27 56 60 75 90 32 60 90 29 81 35  2 16 28 64 15 96 67 74 46 87
  4  7 50 66 96 53 80  5 62 55 42  3  7 76 57 14 11 94 28]
[100  55  41  32  61  65  80  95  37  65  95  34  86  40   7  21  33  69
  20 101  72  79  51  92   9  12  55  71 101  58  85  10  67  60  47   8
  12  81  62  19  16  99  33]


##Broadcasting Rules

In [ ]:
M = np.ones((2, 3))
a = np.arange(3)
print(M)
print(a)

temp = M+a
print(temp)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
M = np.ones((3, 2))
a = np.arange(3)

print(M+a)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
mean_X = units.mean(0)
print(mean_X)

49.325581395348834


In [ ]:
import numpy as np

# Given arrays
celsius_temps = np.array([20, 25, 30, 35])
fahrenheit_temps = np.array([68, 77, 86, 95])

# Convert Celsius to Fahrenheit using broadcasting
fahrenheit_temps_converted = (celsius_temps * 9/5) + 32

# Print the results
print("Celsius Temperatures:", celsius_temps)
print("Fahrenheit Temperatures (original):", fahrenheit_temps)
print("Fahrenheit Temperatures (converted):", fahrenheit_temps_converted)

print(np.array_equal(fahrenheit_temps,fahrenheit_temps_converted))

Celsius Temperatures: [20 25 30 35]
Fahrenheit Temperatures (original): [68 77 86 95]
Fahrenheit Temperatures (converted): [68. 77. 86. 95.]
True


In [ ]:
import numpy as np

# Given arrays
exam_scores = np.array([[85, 90, 88], [78, 85, 80], [92, 88, 95]])
bonus_score = 5

# Calculate average scores with broadcasting
average_scores = np.mean(exam_scores, axis=1)

# Add bonus score to the specific student
exam_scores[0] += bonus_score

print(exam_scores)

# Calculate the new average scores with the bonus
new_average_scores = np.mean(exam_scores, axis=1)

# Print the results
print("Original Average Scores:", average_scores)
print("New Average Scores with Bonus:", new_average_scores)

[[90 95 93]
 [78 85 80]
 [92 88 95]]
Original Average Scores: [87.66666667 81.         91.66666667]
New Average Scores with Bonus: [92.66666667 81.         91.66666667]


##Comparison, Masking, Boolean Logic

In [ ]:
x = np.array([1, 2, 3, 4, 5])

print(x>=3)

print(x!=3)

[False False  True  True  True]
[ True  True False  True  True]


In [ ]:
x = np.array([34, 22, 13, 45, 51, 33, 11])


temp = np.where(x<=25)
print(temp)
temp = np.sum(x<=25)
print(temp)

(array([1, 2, 6]),)
3


In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])
z = np.array([6, 7, 8, 9, 10])

temp = np.any(x==z)
print(temp)
temp = np.all(x==y)
print(temp)

False
True


In [ ]:
print(units)

temp = (units>20)
print(temp)

temp = ((units>20) & (units<80))
print(temp)

[95 50 36 27 56 60 75 90 32 60 90 29 81 35  2 16 28 64 15 96 67 74 46 87
  4  7 50 66 96 53 80  5 62 55 42  3  7 76 57 14 11 94 28]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False  True  True False  True  True  True  True  True
 False False  True  True  True  True  True False  True  True  True False
 False  True  True False False  True  True]
[False  True  True  True  True  True  True False  True  True False  True
 False  True False False  True  True False False  True  True  True False
 False False  True  True False  True False False  True  True  True False
 False  True  True False False False  True]


In [ ]:
import numpy as np

# Create a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access each element using nested for loops
for row in arr:
    for elem in row:
        print(elem)

1
2
3
4
5
6
7
8
9


In [ ]:
import numpy as np

# Create a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flatten the array and access each element
for elem in arr.flatten():
    print(elem)

1
2
3
4
5
6
7
8
9


## Fancy Indeing

In [ ]:
x = np.random.randint(100, size=10)
print(x)

print(x[[0,2,4]])

ind = [0,2,4]
print(x[ind])

[76 33 28 48 74 25 81 56 65 40]
[76 28 74]
[76 28 74]


In [ ]:
X = np.arange(12).reshape((3, 4))
print(X)

row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(X[row, col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  5 11]


##Sorting

In [ ]:
x = np.array([2, 1, 4, 3, 5])

temp = np.sort(x)
print(temp)
print(x)

x.sort()
print(x)

[1 2 3 4 5]
[2 1 4 3 5]
[1 2 3 4 5]


In [ ]:
# Sorted Indices

x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [ ]:
# Row and Column wise sort

rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

# sort each column of X
temp = np.sort(X, axis=0)
print(temp)

# sort each row of X
temp = np.sort(X, axis=1)
print(temp)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]
[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]
